apiVersion: v1
kind: ConfigMap
metadata:
  name: envoyconfig
data:
  envoy.yaml: |
    admin:
      address:
        socket_address: { address: 127.0.0.1, port_value: 15000 }
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:  { address: 0.0.0.0, port_value: 15001 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.tcp_proxy
                  typedConfig:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    cluster: BlockAllCluster
                    statPrefix: BlockAllCluster
          trafficDirection: OUTBOUND
          useOriginalDst: true
      clusters:
        - name: BlockAllCluster
          connect_timeout: 1s
          type: Static