apiVersion: v1
kind: Pod
metadata:
  name: outpod
  labels:
    app: outpod
spec:
  restartPolicy: Never
  initContainers:
    - name: init
      image: bgiddings/iptables
      imagePullPolicy: IfNotPresent
      command: [ "sh","-c" ]
      # 当用户不是1337(envoy)时，请求外部的流量重定向到envoy容器里
      args:
        - iptables -t nat -A OUTPUT -m owner --uid-owner 1337 -j RETURN;
          iptables -t nat -A OUTPUT ! -d 127.0.0.1/32 -p tcp -j REDIRECT --to-ports 15001
      securityContext:
        privileged: true
  containers:
    - name: nginx
      image: nginx:1.18-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
    - name: envoyproxy
      image: envoyproxy/envoy-alpine:v1.21.0
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
      volumeMounts:
        - name: envoyconfig
          mountPath: /etc/envoy/
  volumes:
    - name: envoyconfig
      configMap:
        defaultMode: 0655
        name: envoyconfig
---
apiVersion: v1
kind: Service
metadata:
  name: outpod
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:  #service通过selector和pod建立关联
    app: outpod