admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:  { address: 0.0.0.0, port_value: 8080 }
      listener_filters:
        - name: "envoy.filters.listener.http_inspector"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector
      filter_chains:
        - filters:
#            - name: envoy.filters.network.local_ratelimit
#              typed_config:
#                "@type": type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit
#                stat_prefix: local_rate_limiter
#                token_bucket:
#                  max_tokens: 5       # 桶数量
#                  tokens_per_fill: 1  # 每1秒向桶放1个令牌
#                  fill_interval:
#                    seconds: 1
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: myroute
                  response_headers_to_add:
                    - header:
                        key: myname
                        value: txl
                  virtual_hosts:
                    - name: myhost
                      domains: ["*"]
                      cors:
                        allow_origin_string_match:
                          - exact: "*"
                        allow_methods: "GET, PUT, DELETE, POST, OPTIONS"
                      routes:
                        - match: {prefix: "/v1"}
                          route:
                            cluster: lain_cluster_config
                            # prefix_rewrite: "/"
                            regex_rewrite:
                              pattern:
                                google_re2:
                                  max_program_size: 100
                                regex: "^/v1/(.*?)$"
                              substitution: "/\\1.html"
                      typed_per_filter_config:
                        envoy.filters.http.local_ratelimit:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                          stat_prefix: v1_local_rate_limiter
                          token_bucket:
                            max_tokens: 5
                            tokens_per_fill: 1
                            fill_interval: 1s
                          filter_enabled:
                            runtime_key: local_rate_limit_enabled
                            default_value:
                              numerator: 100
                              denominator: HUNDRED
                          filter_enforced:
                            runtime_key: local_rate_limit_enforced
                            default_value:
                              numerator: 100
                              denominator: HUNDRED
                          response_headers_to_add:
                            - append: false
                              header:
                                key: x-local-rate-limit
                                value: 'true'
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.local_ratelimit
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                      stat_prefix: http_local_rate_limiter
                  - name: addheader.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        function envoy_on_response(response_handle)
                          response_handle:headers():add("myage", "18")
                        end
                  - name: envoy.filters.http.router
  clusters:
    - name: lain_cluster_config
      connect_timeout: 1s
      type: Static
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: lain_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 172.17.0.2
                      port_value: 80
                load_balancing_weight: 2
              - endpoint:
                  address:
                    socket_address:
                      address: 172.17.0.3
                      port_value: 80
                load_balancing_weight: 4